query getEvent($package_price_size_id: Int) {
  finishingsbyquantity(package_price_size_id: $package_price_size_id) {
    id
    option_title
    finishing
    price
    days
    selectedOption {
      id
      title
      price
      days
      option {
        id
        title
        media {
          id
          file_name
          collection_name
        }
      }
    }
  }
}
