query  {
  menus(orderBy:
      [
        { field: "id", order: ASC }
      ],
    	status:1
  	) {
    id
    slug
    title
    link
    categories {
      id
      title
      slug
      subcategories {
          id
          title
          slug
          subtitle
          body
          slug
          media{
            id
            file_name
            collection_name
          }
          label {
            id
            title
            color
        }
      }
      label {
          id
          title
          color
      }
      products {
        id
        title
        slug
        title_two
        body_title
        body_subtitle
        type
        pricing_type
        rule_of_120
        label {
          id
          title
          color
      }
        packages {
          id
          quantity
          prices {
            id
            price
            quantity
            sizes {
                id
                price
            }
            size {
              id
              region
              unit
              portrait
              landscape
            }
          }
        }
        points {
          id
          title
          body
          media{
            id
            file_name
          }
        }
        media{
          id
          file_name
          collection_name
        }
      }
    }
    label {
      id
      title
      color
    }
  }
}
