query {
  products {
    id
    title
    title_two
    slug
    body_title
    body_subtitle
    delivery_time
    quantity
    status
    pricing_type
    rule_of_120
    created_at
    category {
        id
        title
        menu {
            id
            title
        }
    }
    label {
      title
      color
    }
  }
}
