query{
  TopBanners {
    id
    title
    products {
        id
        title
        slug
        title_two
        body_title
        body_subtitle
        media{
          id
          file_name
          collection_name
        }
        packages {
          id
          quantity
          paper {
            id
            title
            side
          }
          prices {
            id
            price
            size {
              id
              region
              unit
              portrait
              landscape
            }
          }
        }
        points {
          id
          title
          body
          media{
            id
            file_name
          }
        }

      }
  }
}
