query ($menu: Int!) {
  TopProducts(menu: $menu) {
    id
    title
    slug
    subcategories {
        id
        title
        slug
    }
    menu {
        id
        title
    }
    products {
        id
        title
        unique_code
        gender
        material
        neck
        cloth_type
        brand
        slug
        title_two
        body_title
        body_subtitle
        pricing_type
        rule_of_120
        status
        delivery_time
        media{
          id
          file_name
          collection_name
        }
        variants {
            id,
            title
            short_title
            stock
            price
            color {
                id
                title
                hex
            }
        }
        category {
            id
            title
            slug
            menu {
                id,
                title
            }
        }
        packages {
          id
          quantity
          paper {
            id
            title
            side
          }
          prices {
            id
            quantity
            sizes {
                id
                price
            }
            size {
              id
              region
              unit
              portrait
              landscape
            }
          }
        }
        points {
          id
          title
          body
          media{
            id
            file_name
          }
        }

      }
  }
}
