query {
  categories(orderBy: [{ field: "created_at", order: DESC }]) {
    id
    title
    slug
    status
    featured
    created_at
    menu {
      id
      title
    }
    label {
      id
      title
      color
    }
  }
}
