query {
  finishings (orderBy: [{ field: "created_at", order: DESC }]) {
    id
    title
    body
    video_link
    delivery_time
    status
    options{
        title
        price
        days
        media {
            id
            name
            file_name
        }
    }
  }
}
