query getEvent($status: String!, $term: String, $search_by: String) {
  manageorders (status: $status, term: $term, search_by: $search_by) {
    id
    title
    price_total
    status
    id
    title
    paper_size
    paper_color
    paper
    paper_quantity
    paper_finishings
    shirt_color
    shirt_sizes
    shirt_printings
    turnaround
    price_product
    price_extra
    price_printing
    price_vat
    price_total
    product_type
    user_id
    status
    gift_quantity
    gift_color
    is_design
    message
    transaction_id
    payment_method_id
    created_at
    user {
      id
      name
    }
    files {
      id
      title
      title
      cloud
      status
    }
    product {
        id
        title
        title_two
        slug
        body_title
        body_subtitle
        delivery_time
        quantity
        type
        status
        created_at
    }
  }
}
