query getEvent($id: ID!) {
  package(id: $id) {
  	id
    quantity
    paper {
        id
        title
    }
    product {
        selectedFinishings {
            id
            options {
                id
                title
                slug
                price
                days
                option {
                    id
                    title
                    price
                    days
                }
            }
            finishing {
                title
            }
      }
      category {
          id
        menu {
          id
          title
        }
      }
    }
  }
}
