query getEvent($id: ID!) {
  package(id: $id) {
  	id
    quantity
    paper {
        id
        title
    }
    product {
      category {
        menu {
          id
          title
        }
      }
    }
  }
}
