query getEvent($type: String!) {
  slidersbytype (type: $type) {
    id
    title
    link
    product{
      id
      title
      slug
      media {
      	id
      	name
      	collection_name
      	file_name
    	}
    }
    media {
      id
      name
      collection_name
      file_name
    }
  }
}
